### ISSUE TITLE
[Bug]: vLLM Docker Version v0.7.2+Gaudi-1.21.2 Fails

### ISSUE THREAD

**Issue by CalebXDonoho** [HabanaAI/vllm-fork#1523]
### Your current environment

**Version:** v0.7.2+Gaudi-1.21.2
**Device:** Gaudi 2
**OS:** Ubuntu

### 🐛 Describe the bug

**Version:** v0.7.2+Gaudi-1.21.2
**Replication Steps:** 
git clone https://github.com/HabanaAI/vllm-fork.git
cd vllm-fork
git checkout v0.7.2+Gaudi-1.21.2
sudo docker build -f docker/Dockerfile.hpu --no-cache -t vllm-ubuntu-env-1-212  .
**Error:** inability to parse tag GAUDI_v1.21.2_76
**Reconfirm:** git tag --merged shows GAUDI_v1.21.2_76, which is not seen under habana_main, nor the v1.21.0 version
**Resolution:** error can be resolved either by modifying the tag or by modifying the setup.py script to parse properly or fallback to a version string able to be properly parsed.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by michalkuligowski** [comment]
Fixed, please try again

**Comment by CalebXDonoho** [comment]
Hello, this appears to still be present. Having attempted tests- this appears to be the case with 0.7.2 and the recent release of 0.8.5. Attempting a command git tag --merged shows **GAUDI_v1.21.2_76**, which may be the source still. Attempting git fetch and git restore does not appear to resolve. Does it require deletion then re-cloning or are there some different steps required?
